name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o favfreak-linux
          GOOS=windows GOARCH=amd64 go build -o favfreak-windows.exe
          GOOS=darwin GOARCH=amd64 go build -o favfreak-macos

      - name: Upload Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: favfreak
          path: |
            favfreak-linux
            favfreak-windows.exe
            favfreak-macos
